# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI ALL THE CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: [ "main" ]

jobs:
  node-app:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm ci --prefix frontend
    - name: Install npm packages
      run: npm --prefix frontend install
    - name: Uglify Javascript
      run:
        npm install javascript-obfuscator -g
        javascript-obfuscator frontend/src/app.js
        javascript-obfuscator frontend/src/file-upload-button.js
        javascript-obfuscator frontend/src/jakob-nielsen-nightmare.js
        javascript-obfuscator frontend/src/timeline-message.js
    - name: Restart node app
      id: restart-node
      run: pm2 restart node-app
      continue-on-error: true
    - name: Start node app
      if: steps.restart-node.outcome != 'success'
      run: pm2 start 'npm run --prefix frontend serve' --name node-app
  kotlin-job:
    runs-on: self-hosted
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      id: setup-gradle
      with:
        gradle-version: release-candidate
    - name: Build with Gradle
      run: gradle build -p backend/
    - name: Restart kotlin application
      id: restart-kt
      run: pm2 restart kotlin-app
      continue-on-error: true
    - name: Start kotlin app
      if: steps.restart-kt.outcome != 'success'
      run: pm2 start 'gradle run -p backend/' --name kotlin-app
