# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI ALL THE CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: [ "main" ]

jobs:
  node-app:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    - run: npm ci --prefix frontend
    - name: Install npm packages
      run: npm --prefix frontend install
    - name: Restart node app
      run: pm2 restart node-app
      continue-on-error: true
    - name: Start node app
      if: failure()
      run: pm2 start 'npm run --prefix frontend serve' --name node-app
  kotlin-job:
    runs-on: self-hosted
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      id: setup-gradle
      with:
        gradle-version: release-candidate
    - name: Build with Gradle
      run: gradle build -p backend/
    - name: Restart kotlin application
      run: pm2 restart kotlin-app
      continue-on-error: true
    - name: Start kotlin app
      if: failure()
      run: pm2 start 'gradle run -p backend/' --name kotlin-app
